import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Select weights you need
  variable: "--font-poppins", // Optional: for Tailwind
});

export const metadata: Metadata = {
  title: "Medicine Corner",
  description: "Generated by NextJS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-gray-50`}
      >
        <Navbar/>

        <main className="flex-grow">
          {children}
        </main>

        <Footer/>
        
      </body>
    </html>
  );
}
